version: "3.1"
services:  
  mongo:
    container_name: mongod-latest
    image: mongo
    restart: always
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: toor
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
      - mongodb-config:/data/configdb
      - ./mongod.conf:/etc/mongod.conf
    entrypoint: ["mongod","--config","/etc/mongod.conf"]
volumes:
  mongodb-data:
  mongodb-config:

  